 tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      source ./bin/set_tf_alias
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: http-server
    before: |
      npm install --global http-server
      http-server 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph

    