variable "terratowns_endpoint" {
  type = string
}

variable "terratowns_access_token" {
  description = "Your own access token generated by the vending machine from teacherseat."
  type        = string
}

variable "teacherseat_user_uuid" {
  description = "Your own user uuid from teacherseat."
  type        = string
}

variable "nomadiachi" {
  type = object({
    public_path = string
    content_version = number
  })
}

variable "voices" {
  type = object({
    public_path = string
    content_version = number
  })
}
