variable "terratowns_endpoint" {
  type = string
}

variable "teacherseat_user_uuid" {
  description = "Your own user uuid from teacherseat."
  type        = string
}

variable "terratowns_access_token" {
  description = "Your own access token generated by the vending machine from teacherseat."
  type        = string
}

variable "bucket_name" {
  type = string
}

variable "index_html_filepath" {
  type = string
}

variable "error_html_filepath" {
  type = string
}

variable "content_version" {
  type = number
}

variable "assets_path" {
  description = "path to public/assets which stores images."
  type        = string
}
